# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='duel',
  syntax='proto2',
  serialized_pb=_b('\n\rmessage.proto\x12\x04\x64uel\"L\n\x08RouteMsg\x12\x1e\n\x07request\x18\x01 \x01(\x0b\x32\r.duel.Request\x12 \n\x08response\x18\x02 \x01(\x0b\x32\x0e.duel.Response\"}\n\x07Request\x12&\n\x0bregisterReq\x18\x01 \x01(\x0b\x32\x11.duel.RegisterReq\x12 \n\x08loginReq\x18\x02 \x01(\x0b\x32\x0e.duel.LoginReq\x12(\n\x0creconnectReq\x18\x03 \x01(\x0b\x32\x12.duel.ReconnectReq\"\xbb\x01\n\x08Response\x12\x0e\n\x06result\x18\x01 \x02(\x08\x12\x14\n\x0clastResponse\x18\x02 \x02(\x08\x12\x15\n\rerrorDescribe\x18\x03 \x01(\t\x12&\n\x0bregisterRes\x18\x04 \x01(\x0b\x32\x11.duel.RegisterRes\x12 \n\x08loginRes\x18\x05 \x01(\x0b\x32\x0e.duel.LoginRes\x12(\n\x0creconnectRes\x18\x06 \x01(\x0b\x32\x12.duel.ReconnectRes\"e\n\x0bNotifaction\x12*\n\rstartGameNoti\x18\x01 \x01(\x0b\x32\x13.duel.StartGameNoti\x12*\n\rpeerLeaveNoti\x18\x02 \x01(\x0b\x32\x13.duel.PeerLeaveNoti\"\r\n\x0bRegisterReq\")\n\x0bRegisterRes\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\"\x18\n\x08LoginReq\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"\n\n\x08LoginRes\"\x1c\n\x0cReconnectReq\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"\x0e\n\x0cReconnectRes\"3\n\rStartGameNoti\x12\x10\n\x08peerUuid\x18\x01 \x02(\t\x12\x10\n\x08peerName\x18\x02 \x02(\t\"\x0f\n\rPeerLeaveNoti*\xb8\x01\n\x03Msg\x12\x12\n\x0cRegister_Req\x10\x81\x80\x04\x12\x12\n\x0cRegister_Res\x10\x82\x80\x04\x12\x0f\n\tLogin_Req\x10\x83\x80\x04\x12\x0f\n\tLogin_Res\x10\x84\x80\x04\x12\x13\n\rReconnect_Req\x10\x85\x80\x04\x12\x13\n\rReconnect_Res\x10\x86\x80\x04\x12\x15\n\x0fStart_Game_Noti\x10\xf0\x81\x04\x12\x15\n\x0fPeer_Leave_Noti\x10\xf1\x81\x04\x12\x0f\n\tRoute_Msg\x10\x80\xa0\x04\x42\x1a\n\x18\x63om.kongyt.duel.messages')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSG = _descriptor.EnumDescriptor(
  name='Msg',
  full_name='duel.Msg',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Register_Req', index=0, number=65537,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Register_Res', index=1, number=65538,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_Req', index=2, number=65539,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Login_Res', index=3, number=65540,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reconnect_Req', index=4, number=65541,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Reconnect_Res', index=5, number=65542,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Start_Game_Noti', index=6, number=65776,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Peer_Leave_Noti', index=7, number=65777,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Route_Msg', index=8, number=69632,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=734,
  serialized_end=918,
)
_sym_db.RegisterEnumDescriptor(_MSG)

Msg = enum_type_wrapper.EnumTypeWrapper(_MSG)
Register_Req = 65537
Register_Res = 65538
Login_Req = 65539
Login_Res = 65540
Reconnect_Req = 65541
Reconnect_Res = 65542
Start_Game_Noti = 65776
Peer_Leave_Noti = 65777
Route_Msg = 69632



_ROUTEMSG = _descriptor.Descriptor(
  name='RouteMsg',
  full_name='duel.RouteMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='duel.RouteMsg.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='duel.RouteMsg.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=99,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='duel.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='registerReq', full_name='duel.Request.registerReq', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginReq', full_name='duel.Request.loginReq', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reconnectReq', full_name='duel.Request.reconnectReq', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=226,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='duel.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='duel.Response.result', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lastResponse', full_name='duel.Response.lastResponse', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorDescribe', full_name='duel.Response.errorDescribe', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='registerRes', full_name='duel.Response.registerRes', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loginRes', full_name='duel.Response.loginRes', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reconnectRes', full_name='duel.Response.reconnectRes', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=416,
)


_NOTIFACTION = _descriptor.Descriptor(
  name='Notifaction',
  full_name='duel.Notifaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startGameNoti', full_name='duel.Notifaction.startGameNoti', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peerLeaveNoti', full_name='duel.Notifaction.peerLeaveNoti', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=519,
)


_REGISTERREQ = _descriptor.Descriptor(
  name='RegisterReq',
  full_name='duel.RegisterReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=521,
  serialized_end=534,
)


_REGISTERRES = _descriptor.Descriptor(
  name='RegisterRes',
  full_name='duel.RegisterRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='duel.RegisterRes.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='duel.RegisterRes.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=536,
  serialized_end=577,
)


_LOGINREQ = _descriptor.Descriptor(
  name='LoginReq',
  full_name='duel.LoginReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='duel.LoginReq.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=603,
)


_LOGINRES = _descriptor.Descriptor(
  name='LoginRes',
  full_name='duel.LoginRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=615,
)


_RECONNECTREQ = _descriptor.Descriptor(
  name='ReconnectReq',
  full_name='duel.ReconnectReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='duel.ReconnectReq.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=645,
)


_RECONNECTRES = _descriptor.Descriptor(
  name='ReconnectRes',
  full_name='duel.ReconnectRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=661,
)


_STARTGAMENOTI = _descriptor.Descriptor(
  name='StartGameNoti',
  full_name='duel.StartGameNoti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peerUuid', full_name='duel.StartGameNoti.peerUuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peerName', full_name='duel.StartGameNoti.peerName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=663,
  serialized_end=714,
)


_PEERLEAVENOTI = _descriptor.Descriptor(
  name='PeerLeaveNoti',
  full_name='duel.PeerLeaveNoti',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=731,
)

_ROUTEMSG.fields_by_name['request'].message_type = _REQUEST
_ROUTEMSG.fields_by_name['response'].message_type = _RESPONSE
_REQUEST.fields_by_name['registerReq'].message_type = _REGISTERREQ
_REQUEST.fields_by_name['loginReq'].message_type = _LOGINREQ
_REQUEST.fields_by_name['reconnectReq'].message_type = _RECONNECTREQ
_RESPONSE.fields_by_name['registerRes'].message_type = _REGISTERRES
_RESPONSE.fields_by_name['loginRes'].message_type = _LOGINRES
_RESPONSE.fields_by_name['reconnectRes'].message_type = _RECONNECTRES
_NOTIFACTION.fields_by_name['startGameNoti'].message_type = _STARTGAMENOTI
_NOTIFACTION.fields_by_name['peerLeaveNoti'].message_type = _PEERLEAVENOTI
DESCRIPTOR.message_types_by_name['RouteMsg'] = _ROUTEMSG
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Notifaction'] = _NOTIFACTION
DESCRIPTOR.message_types_by_name['RegisterReq'] = _REGISTERREQ
DESCRIPTOR.message_types_by_name['RegisterRes'] = _REGISTERRES
DESCRIPTOR.message_types_by_name['LoginReq'] = _LOGINREQ
DESCRIPTOR.message_types_by_name['LoginRes'] = _LOGINRES
DESCRIPTOR.message_types_by_name['ReconnectReq'] = _RECONNECTREQ
DESCRIPTOR.message_types_by_name['ReconnectRes'] = _RECONNECTRES
DESCRIPTOR.message_types_by_name['StartGameNoti'] = _STARTGAMENOTI
DESCRIPTOR.message_types_by_name['PeerLeaveNoti'] = _PEERLEAVENOTI
DESCRIPTOR.enum_types_by_name['Msg'] = _MSG

RouteMsg = _reflection.GeneratedProtocolMessageType('RouteMsg', (_message.Message,), dict(
  DESCRIPTOR = _ROUTEMSG,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.RouteMsg)
  ))
_sym_db.RegisterMessage(RouteMsg)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.Response)
  ))
_sym_db.RegisterMessage(Response)

Notifaction = _reflection.GeneratedProtocolMessageType('Notifaction', (_message.Message,), dict(
  DESCRIPTOR = _NOTIFACTION,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.Notifaction)
  ))
_sym_db.RegisterMessage(Notifaction)

RegisterReq = _reflection.GeneratedProtocolMessageType('RegisterReq', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERREQ,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.RegisterReq)
  ))
_sym_db.RegisterMessage(RegisterReq)

RegisterRes = _reflection.GeneratedProtocolMessageType('RegisterRes', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERRES,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.RegisterRes)
  ))
_sym_db.RegisterMessage(RegisterRes)

LoginReq = _reflection.GeneratedProtocolMessageType('LoginReq', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQ,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.LoginReq)
  ))
_sym_db.RegisterMessage(LoginReq)

LoginRes = _reflection.GeneratedProtocolMessageType('LoginRes', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRES,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.LoginRes)
  ))
_sym_db.RegisterMessage(LoginRes)

ReconnectReq = _reflection.GeneratedProtocolMessageType('ReconnectReq', (_message.Message,), dict(
  DESCRIPTOR = _RECONNECTREQ,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.ReconnectReq)
  ))
_sym_db.RegisterMessage(ReconnectReq)

ReconnectRes = _reflection.GeneratedProtocolMessageType('ReconnectRes', (_message.Message,), dict(
  DESCRIPTOR = _RECONNECTRES,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.ReconnectRes)
  ))
_sym_db.RegisterMessage(ReconnectRes)

StartGameNoti = _reflection.GeneratedProtocolMessageType('StartGameNoti', (_message.Message,), dict(
  DESCRIPTOR = _STARTGAMENOTI,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.StartGameNoti)
  ))
_sym_db.RegisterMessage(StartGameNoti)

PeerLeaveNoti = _reflection.GeneratedProtocolMessageType('PeerLeaveNoti', (_message.Message,), dict(
  DESCRIPTOR = _PEERLEAVENOTI,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:duel.PeerLeaveNoti)
  ))
_sym_db.RegisterMessage(PeerLeaveNoti)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.kongyt.duel.messages'))
# @@protoc_insertion_point(module_scope)
